name: npm-publish

on:
  release:
    types: [created]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    if: github.repository == 'my-mcp-hub/node-mcp-server'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false

      - name: Install Package
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test Package
        run: npm run coverage

      - name: Pack Package
        run: npm pack

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v7
        with:
          name: npm-package
          path: my-mcp-hub-node-mcp-server-*.tgz

  publish:
    if: github.repository == 'my-mcp-hub/node-mcp-server'
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Download Package Artifact
        uses: actions/download-artifact@v8
        with:
          name: npm-package
          path: .

      - name: Install Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false

      - name: Publish NPM Package
        run: npm publish ./*.tgz --provenance --access public
